### ISSUE TITLE
Shift down does not work

### ISSUE THREAD

**Issue by vPubneutral** [RakambdaOrg/FallingTree#216]
### Describe the bug

When using shift down mode, the block does not break or drop, and the tree does not shift down or change in any way. The durability of the tool is still taken, so it seems like the mod is trying to do something and it just isn't working.

Here's a video showcasing the bug: [Video](https://youtu.be/AenkYBkfiJs)

EDIT: Forgot to mention this, but this happens with a brand new config where the only option changed is setting Break Mode to Shift Down.

### Minecraft version

1.17.1

### Forge version

37.0.70

### Mod version

2.14.0

### Relevant log output

```shell
Neither the debug.log or latest.log had any information relevent to this mod aside from the mod itself being loaded.
```

**Comment by Rakambda** [comment]
I'll look into it a bit later. Just like that, do you know if it was working fine in the previous version?
My guess would be it's because of changes in the 2.14.0 version as I kinda touched a bit that area.

**Comment by vPubneutral** [comment]
I tried every single version of your mod that supports Forge 1.17.1 (2.12.2-2.14.0) and the issue was present in all of them. The feature works fine on my 1.16.5 install with the latest version of your mod for that MC version.

**Comment by Rakambda** [comment]
Weird that it's the jump from the MC version that introduces the bug. Can you share your config file so it'll be easier for me to reproduce later?

EDIT: I can reproduce

**Comment by vPubneutral** [comment]
Saw your edit, gonna send it anyways just in case. Sorry it took so long to get back to you, internet has been kinda wack the past day or two cause of a flood.

```toml
#When set to true, a tree will, only be chopped down if the player is sneaking.
reverse_sneaking = false
#When set to true, the mod will, cut down trees in creative too.
break_in_creative = false
#How messages are sent to the player.
#CHAT: Messages are sent in the chat.
#ACTION_BAR: Messages are displayed in the player's action bar.
#Allowed Values: CHAT, ACTION_BAR
notification_mode = "ACTION_BAR"

#Falling Tree configuration
[trees]
	#How to break the tree.
	#INSTANTANEOUS will break it in one go.
	#SHIFT_DOWN will make the tree fall down as you cut it, so you still have to break x blocks but don't have to climb the tree for them.
	#Allowed Values: INSTANTANEOUS, SHIFT_DOWN
	break_mode = "SHIFT_DOWN"
	#What part of the tree should be cut.
	#WHOLE_TREE tree will break the whole tree.
	#ABOVE_CUT will break only blocks that are connected from above the cut point.
	#ABOVE_Y will break only blocks that are above the y value of the cut point.
	#Allowed Values: WHOLE_TREE, ABOVE_CUT, ABOVE_Y
	detection_mode = "WHOLE_TREE"
	#Additional list of blocks considered as logs and that will be destroyed by the mod.
	#INFO: Blocks marked with the log tag will already be whitelisted.
	logs_whitelisted = []
	#List of blocks that should not be considered as logs.
	#INFO: This wins over the whitelist.
	logs_blacklisted = []
	#Additional list of blocks considered as leaves (decay naturally).
	#INFO: Blocks marked with the leaves tag will already be whitelisted.
	leaves_whitelisted = []
	#Additional list of blocks considered as leaves but that doesn't decay (need to be broken by tool).
	leaves_non_decay_whitelisted = []
	#List of blocks that should not be considered as leaves.
	#INFO: This wins over the whitelist.
	leaves_blacklisted = []
	#The maximum number of blocks to scan when trying to detect a tree. If there's more than this value the tree won't be cut.
	#Range: > 1
	max_scan_size = 500
	#The maximum size of a tree. If there's more logs than this value the max size action will be applied.
	#Range: > 1
	logs_max_count = 100
	#What to do when the max size of a tree is reached.
	#ABORT: Tree won't be cut.
	#CUT: Tree will still be cut leaving some of it untouched.
	#Allowed Values: ABORT, CUT
	max_size_action = "ABORT"
	#In what order logs are broken.
	#This only makes sense if maxSize < maxScanSize.
	#FURTHEST_FIRST: The furthest log will be broken first.
	#CLOSEST_FIRST: The closest log will be broken first.
	#INFO: Only in INSTANTANEOUS mode.
	#Allowed Values: FURTHEST_FIRST, CLOSEST_FIRST
	break_order = "FURTHEST_FIRST"
	#When set to true, the mod will cut trees with one cut.
	tree_breaking = true
	#When set to true, leaves that should naturally break will be broken instantly.
	leaves_breaking = true
	#Radius to force break leaves. If another tree is still holding the leaves they'll still be broken.
	#If the leaves are persistent (placed by player) they'll also be destroyed.
	#The radius is applied from one of the top most log blocks.
	#INFO: break_leaves must be activated for this to take effect.
	#INFO: Only in INSTANTANEOUS mode.
	#Range: 0 ~ 10
	leaves_breaking_force_radius = 0
	#The minimum amount of leaves that needs to be around the top most log in order for the mod to consider it a tree.
	#INFO: Only in INSTANTANEOUS mode.
	#Range: 0 ~ 5
	minimum_leaves_around_required = 1
	#When set to true this allow to have any kind of log in a tree trunk.
	#Otherwise (false) the trunk will be considered as being only one kind of log.
	allow_mixed_logs = false
	#When set to true nether tree warts (leaves) will be broken along with the trunk.
	break_nether_tree_warts = true
	#When set to true nether tree warts (leaves) will be broken with only one hit.
	#INFO: Only in SHIFT_DOWN mode.
	instantly_break_warts = false
	#This defines the area in which the tree is searched. If any branch is going out of this area it won't be cut.
	#This value is the radius of the area.
	#i.e. Setting a value of 2 will result on an area of 3x3 centered on the log broken.
	#If this value is set to a negative number then no area restriction will be applied.
	#Range: > -2147483648
	search_around_radius = -1
	#List the blocks that can be against the tree. If something else is adjacent then the tree won't be cut.
	#INFO: Use adjacentStopMode to define how we stop the search for the tree.
	adjacent_blocks_whitelisted = []
	#What to do when an non whitelisted adjacent block is found.
	#STOP_ALL will stop the search and nothing will be cut.
	#STOP_BRANCH will stop the current branch only. The rest of the tree will be cut.
	#Allowed Values: STOP_ALL, STOP_BRANCH
	adjacent_stop_mode = "STOP_ALL"

[tools]
	#When set to true, the mod will be activated no matter what you have in your hand.
	#INFO: Blacklist still can be use to restrict some tools.
	ignore_tools = false
	#Additional list of tools that can be used to chop down a tree.
	#INFO: Items marked with the axe tag will already be whitelisted.
	whitelisted = []
	#List of tools that should not be considered as tools.
	#INFO: This wins over the whitelist.
	blacklisted = []
	#Defines the number of times the damage is applied to the tool.
	#ie: if set to 1 then breaking 5 logs will give 5 damage.
	#ie: if set to 2 then breaking 5 logs will give 10 damage.
	#If set to 0, it'll still apply 1 damage for every cut.
	#INFO: This only applies when the tree is cut when using the mod.
	#Range: 0.0 ~ 100.0
	damage_multiplicand = 1.0
	#How damage taken should be rounded if it isn't a whole number.
	#ROUNDING will round to the closest whole number.
	#ROUND_DOWN will round down.
	#ROUND_UP will round up.
	#PROBABILISTIC will treat decimal fraction as a probability of rounding up.
	#ie: 9.45 will have 45% chance of being rounded up to 10 and 55% chance of being rounded down to 9.
	#Allowed Values: ROUNDING, ROUND_UP, ROUND_DOWN, PROBABILISTIC
	damage_rounding = "ROUND_DOWN"
	#Applies a speed modifier when breaking the tree.
	#0 will disable this, so the speed will be the default one of breaking a block.
	#If set to 1 each log block will be counted once, so if the tree is 5 blocks tall it'll require the time of breaking 5 logs.
	#If set to 2 each log block will be counted twice, so if the tree is 5 blocks tall, it'll require the time of breaking 10 logs
	#INFO: Only in INSTANTANEOUS mode.
	#WARNING: If you are on a server, this either has to be set to 0 or every player should have the mod. Else they'll have a weird effect of breaking the block but the block is still there.
	#Range: 0.0 ~ 50.0
	speed_multiplicand = 0.0
	#When set to true, when a tree is broken and the tool is about to break we will just break enough blocks so that the tool is left at 1 of durability.
	#INFO: Only in instantaneous mode
	preserve = false
```
